-- MySQL Script generated by MySQL Workbench
-- Wed Dec  2 23:34:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- METROPOLITAN COMMUNITY COLLEGE
-- CSIS 279–WEB_DATABASE_PROGRAMMING
-- Student Name: Juan Lepe
-- Student ID: S1448233 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema csis279_final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csis279_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csis279_final` DEFAULT CHARACTER SET utf8 ;
USE `csis279_final` ;

-- -----------------------------------------------------
-- Table `csis279_final`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csis279_final`.`user_type` ;

CREATE TABLE IF NOT EXISTS `csis279_final`.`user_type` (
  `id` INT NOT NULL,
  `user_type_name` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csis279_final`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csis279_final`.`job` ;

CREATE TABLE IF NOT EXISTS `csis279_final`.`job` (
  `id` INT NOT NULL,
  `category` VARCHAR(45) NULL,
  `job` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csis279_final`.`user_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csis279_final`.`user_account` ;

CREATE TABLE IF NOT EXISTS `csis279_final`.`user_account` (
  `id` INT NOT NULL,
  `user_type_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(100) NULL,
  `date_of_birth` DATE NULL,
  `gender` CHAR(1) NULL,
  `is_active` CHAR(1) NULL,
  `contact_number` INT NULL,
  `sms_notification_active` CHAR(1) NULL,
  `email_notification_active` CHAR(1) NULL,
  `user_image` BLOB NULL,
  `registration_date` DATE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_account_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `csis279_final`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_account_job1`
    FOREIGN KEY (`job_id`)
    REFERENCES `csis279_final`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_account_user_type1_idx` ON `csis279_final`.`user_account` (`user_type_id` ASC) ;

CREATE INDEX `fk_user_account_job1_idx` ON `csis279_final`.`user_account` (`job_id` ASC) ;


-- -----------------------------------------------------
-- Table `csis279_final`.`user_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csis279_final`.`user_log` ;

CREATE TABLE IF NOT EXISTS `csis279_final`.`user_log` (
  `user_accout_id` INT NOT NULL,
  `last_login_date` VARCHAR(45) NULL,
  `last_job_apply_date` VARCHAR(45) NULL,
  `user_account_id` INT NOT NULL,
  PRIMARY KEY (`user_accout_id`),
  CONSTRAINT `fk_user_log_user_account`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `csis279_final`.`user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_log_user_account_idx` ON `csis279_final`.`user_log` (`user_account_id` ASC) ;


-- -----------------------------------------------------
-- Table `csis279_final`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csis279_final`.`company` ;

CREATE TABLE IF NOT EXISTS `csis279_final`.`company` (
  `id` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csis279_final`.`company_job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csis279_final`.`company_job` ;

CREATE TABLE IF NOT EXISTS `csis279_final`.`company_job` (
  `id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_company_job_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `csis279_final`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_job_job1`
    FOREIGN KEY (`job_id`)
    REFERENCES `csis279_final`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_company_job_company1_idx` ON `csis279_final`.`company_job` (`company_id` ASC) ;

CREATE INDEX `fk_company_job_job1_idx` ON `csis279_final`.`company_job` (`job_id` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `csis279_final`.`job` (`category`, `job`, `description`) VALUES ('Systems', 'Systems', 'Developer');
INSERT INTO `csis279_final`.`job` (`category`, `job`, `description`) VALUES ('Production', 'Administrative', 'Administrative');

